# Generated by Django 5.2.7 on 2025-10-31 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastName', models.CharField(max_length=120)),
                ('firstName', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('postalZip', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=60, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('publicUrl', models.URLField(blank=True, null=True)),
                ('creditCard', models.CharField(blank=True, max_length=50, null=True)),
                ('cvv', models.PositiveIntegerField(blank=True, null=True)),
                ('pin', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('cars', models.PositiveSmallIntegerField(default=0)),
                ('bio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
